apiVersion: v1
kind: Secret
metadata:
  name: springboot-secret
type: Opaque
data:
  db-password: cGFzc3dvcmQ=   # base64 of 'password'
stringData:
    app.secret: "Secret: This message is from K8s Secret"